import Link from "next/link";
import { ContactLink, LegalPage, Operator } from "@/components/legal";
import { proOffer, site } from "@/lib/site";

export const metadata = { title: "Terms of Service" };

export default function Terms() {
  const pro = proOffer();
  return (
    <LegalPage title="Terms of Service">
      <p>
        These terms apply when you use {site.name} at {site.url} (the &ldquo;Service&rdquo;). <Operator />. By creating an account or using
        the Service you agree to these terms. If you don&apos;t agree, please don&apos;t use the Service.
      </p>

      <h2>1. The Service</h2>
      <p>
        {site.name} turns a short description, and optionally your website and logo, into a motion-graphics video: it writes a script with
        AI, records a synthetic voiceover, adds music and sound effects, animates the scenes and renders a video file you can download.
      </p>

      <h2>2. Your account</h2>
      <ul>
        <li>You must be at least 18 years old, or have permission from a parent or guardian, and able to enter a binding contract.</li>
        <li>Give a real email address and keep your password safe. You are responsible for what happens in your account.</li>
        <li>One person per account. Don&apos;t create several accounts to get around plan limits.</li>
      </ul>

      <h2>3. Your content</h2>
      <ul>
        <li>
          You keep the rights to what you put in: prompts, text, logos, images and website addresses (&ldquo;Your Content&rdquo;). You give us
          permission to use it only to run the Service for you, including sending prompts to our AI provider.
        </li>
        <li>
          You must have the right to use Your Content and any brand, logo or website you ask us to read. Don&apos;t make videos for a brand
          you don&apos;t represent or have permission from.
        </li>
        <li>
          The videos the Service makes for you are yours to use, including commercially, subject to the third-party licences listed in the
          <code> credits.txt</code> file that comes with each video (for example, some music needs an attribution line). Keep those credits
          when you publish.
        </li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>Don&apos;t use the Service to make or share content that:</p>
      <ul>
        <li>is illegal, defamatory, obscene, hateful, harassing or violent, or harms children;</li>
        <li>infringes someone else&apos;s copyright, trademark, privacy or other rights;</li>
        <li>impersonates a person or organisation, or is meant to mislead (including fake reviews, testimonials or statistics);</li>
        <li>promotes scams, malware, gambling or anything else unlawful in India or where it is shown.</li>
      </ul>
      <p>
        Don&apos;t try to break, overload, scrape or reverse-engineer the Service, or get around its limits. We may suspend or close accounts
        that break these rules.
      </p>

      <h2>5. AI output</h2>
      <p>
        Scripts and voiceovers are generated by AI and can contain mistakes. Check every video before you publish it; you are responsible for
        what you publish.
      </p>

      <h2>6. Plans and payment</h2>
      <ul>
        <li>The Free plan has monthly render and daily AI request limits, shown in the app and on the pricing section.</li>
        <li>
          The Pro pass costs ₹{pro.priceInr.toLocaleString("en-IN")} (including applicable taxes unless stated otherwise) and gives Pro limits
          for {pro.days} days from payment. It does not renew automatically; buying another pass while Pro is active adds {pro.days} days.
        </li>
        <li>Payments are processed by Razorpay. We don&apos;t see or store your card, UPI or bank details.</li>
        <li>
          Refunds follow our <Link href="/refunds">Refund &amp; Cancellation Policy</Link>.
        </li>
        <li>We may change prices or limits for new purchases; a pass you have already bought keeps its terms.</li>
      </ul>

      <h2>7. Availability</h2>
      <p>
        We work to keep the Service running but don&apos;t promise it will always be available or error-free. Renders can fail; failed renders
        don&apos;t count against your limits. We may change or stop features, and will give reasonable notice before closing the Service.
      </p>

      <h2>8. Liability</h2>
      <p>
        The Service is provided &ldquo;as is&rdquo;. To the extent the law allows, we are not liable for indirect or consequential losses, and
        our total liability to you is limited to the amount you paid us in the 3 months before the claim.
      </p>

      <h2>9. Ending your account</h2>
      <p>
        You can stop using the Service at any time and ask us to delete your account by writing to <ContactLink />. We may suspend or close an
        account that breaks these terms.
      </p>

      <h2>10. Law</h2>
      <p>
        These terms are governed by the laws of India. Disputes go to the courts of {site.jurisdiction}. We may update these terms; if a change
        is significant we will tell you by email or in the app before it applies.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions: <ContactLink />.
      </p>
    </LegalPage>
  );
}
