// The template catalog fed to the director (and written to catalog.md by `pnpm templates:catalog`).
import { z } from "zod";
import { templates } from "./registry.js";

interface JsonSchema {
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  description?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  default?: unknown;
}

function limits(s: JsonSchema): string {
  const parts: string[] = [];
  if (s.minLength !== undefined || s.maxLength !== undefined) parts.push(`${s.minLength ?? 0}-${s.maxLength ?? "∞"} chars`);
  if (s.minimum !== undefined || s.maximum !== undefined) parts.push(`${s.minimum ?? "-∞"} to ${s.maximum ?? "∞"}`);
  if (s.minItems !== undefined || s.maxItems !== undefined) parts.push(`${s.minItems ?? 0}-${s.maxItems ?? "∞"} items`);
  if (s.default !== undefined) parts.push(`default ${JSON.stringify(s.default)}`);
  return parts.join(", ");
}

function rows(schema: JsonSchema, prefix = ""): string[] {
  const out: string[] = [];
  for (const [key, s] of Object.entries(schema.properties ?? {})) {
    const name = `${prefix}${key}`;
    const required = schema.required?.includes(key) ? "yes" : "no";
    const type = s.type === "array" ? `array of ${s.items?.type ?? "item"}` : String(s.type ?? "any");
    out.push(`| \`${name}\` | ${type} | ${required} | ${limits(s)} | ${s.description ?? ""} |`);
    if (s.type === "array" && s.items?.properties) out.push(...rows(s.items, `${name}[].`));
  }
  return out;
}

export function buildCatalog(): string {
  const sections = Object.values(templates).map(({ meta, schema }) => {
    const json = z.toJSONSchema(schema, { io: "input", unrepresentable: "any" }) as JsonSchema;
    return [
      `## ${meta.name}`,
      "",
      `- **Category:** ${meta.category}${meta.category === "hook" ? " (can open the video)" : meta.category === "end" ? " (can close the video)" : ""}`,
      `- **Duration:** ${meta.minDuration}-${meta.maxDuration} s`,
      `- **What it shows:** ${meta.description}`,
      `- **When to use:** ${meta.whenToUse}`,
      "",
      "| Field | Type | Required | Limits | Notes |",
      "|---|---|---|---|---|",
      ...rows(json),
    ].join("\n");
  });

  return `# Template catalog

Generated by \`pnpm templates:catalog\` from packages/templates. Do not edit by hand.

Each scene picks one template and fills its \`content\` with the fields below.
The first scene must be a hook template; the last must be \`logo_reveal\` or \`cta\`;
the same template may not appear twice in a row.

${sections.join("\n\n")}
`;
}
