import catalogJson from "@/generated/catalog.json";

// Generated by scripts/catalog.mts (templates, voices, fonts, ...). Safe for client components.
export interface JsonSchema {
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  description?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  default?: unknown;
  enum?: unknown[];
  pattern?: string;
}

export interface TemplateInfo {
  name: string;
  description: string;
  whenToUse: string;
  category: "hook" | "content" | "end";
  minDuration: number;
  maxDuration: number;
  listField?: string;
  schema: JsonSchema;
  example: { content: Record<string, unknown>; voiceover: string; estDuration: number };
}

export interface Catalog {
  templates: TemplateInfo[];
  voices: { id: string; lang: "en" | "hi"; label: string; rate: number }[];
  speech: { defaultRate: number; pause: number; overhead: number };
  transitions: Record<string, string>;
  formats: string[];
  moods: string[];
  musicMoods: string[];
  icons: string[];
  fonts: string[];
}

export const catalog = catalogJson as unknown as Catalog;
export const templateInfo = (name: string) => catalog.templates.find((t) => t.name === name);

const LABELS: Record<string, string> = { cta: "Call to action", hero_text: "Hero text", feature_grid: "Feature grid", stat_counter: "Stat counter", logo_reveal: "Logo reveal" };
export const templateLabel = (name: string) => LABELS[name] ?? name.replace(/_/g, " ").replace(/^./, (c) => c.toUpperCase());
